/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import donorschooseapplication.project.Category;

/**
 *
 * @author asoual
 */
import static GUI.ProjectsFrame.projects;
import static GUI.DisplayProject.model;
import static GUI.DisplayProject.projectslist;
import donorschooseapplication.project.Project;
import javax.swing.JOptionPane;


public class AddProject extends javax.swing.JPanel {

    /**
     * Creates new form AddProject
     */
    public AddProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        titledescriptiontxt = new javax.swing.JTextField();
        fundingGoaltxt = new javax.swing.JTextField();
        schooltxt = new javax.swing.JTextField();
        gradetxt = new javax.swing.JTextField();
        studentimpactedtxt = new javax.swing.JTextField();
        moneydonatedtxt = new javax.swing.JTextField();
        texttxt = new javax.swing.JTextField();
        categorycombo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        addbtn1 = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Create.png"))); // NOI18N
        jLabel1.setText("Add a New Project");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Title Description");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("type");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("funding Goal");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("School");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("avg Student Grade");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("nb of student Impacted");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Money Donated");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("text");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Category");

        typetxt.setBackground(new java.awt.Color(255, 255, 255));
        typetxt.setForeground(new java.awt.Color(51, 51, 51));

        titledescriptiontxt.setBackground(new java.awt.Color(255, 255, 255));
        titledescriptiontxt.setForeground(new java.awt.Color(51, 51, 51));
        titledescriptiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titledescriptiontxtActionPerformed(evt);
            }
        });

        fundingGoaltxt.setBackground(new java.awt.Color(255, 255, 255));
        fundingGoaltxt.setForeground(new java.awt.Color(51, 51, 51));

        schooltxt.setBackground(new java.awt.Color(255, 255, 255));
        schooltxt.setForeground(new java.awt.Color(51, 51, 51));

        gradetxt.setBackground(new java.awt.Color(255, 255, 255));
        gradetxt.setForeground(new java.awt.Color(51, 51, 51));
        gradetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradetxtActionPerformed(evt);
            }
        });

        studentimpactedtxt.setBackground(new java.awt.Color(255, 255, 255));
        studentimpactedtxt.setForeground(new java.awt.Color(51, 51, 51));

        moneydonatedtxt.setBackground(new java.awt.Color(255, 255, 255));
        moneydonatedtxt.setForeground(new java.awt.Color(51, 51, 51));

        texttxt.setBackground(new java.awt.Color(255, 255, 255));
        texttxt.setForeground(new java.awt.Color(51, 51, 51));

        categorycombo.setBackground(new java.awt.Color(255, 255, 255));
        categorycombo.setForeground(new java.awt.Color(51, 51, 51));
        categorycombo.setModel(new javax.swing.DefaultComboBoxModel<>(Category.values()));

        addbtn1.setBackground(new java.awt.Color(255, 255, 255));
        addbtn1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        addbtn1.setForeground(new java.awt.Color(0, 0, 0));
        addbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Create.png"))); // NOI18N
        addbtn1.setText("Add");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(255, 255, 255));
        clearbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(51, 51, 51));
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Abort.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titledescriptiontxt)
                    .addComponent(typetxt)
                    .addComponent(fundingGoaltxt)
                    .addComponent(schooltxt)
                    .addComponent(gradetxt)
                    .addComponent(studentimpactedtxt)
                    .addComponent(moneydonatedtxt)
                    .addComponent(texttxt)
                    .addComponent(categorycombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(addbtn1)
                        .addGap(88, 88, 88)
                        .addComponent(clearbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titledescriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fundingGoaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(schooltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentimpactedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(moneydonatedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn1)
                    .addComponent(clearbtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titledescriptiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titledescriptiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titledescriptiontxtActionPerformed

    private void gradetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradetxtActionPerformed

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
        // TODO add your handling code here:

        String title_description = titledescriptiontxt.getText();
        if (title_description.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid title", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type = typetxt.getText();
        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid type", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fundingGoalstr = fundingGoaltxt.getText();
        double fundingGoal;
        try {
            fundingGoal = Double.parseDouble(fundingGoalstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid funding Goal", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String School = schooltxt.getText();
        if (School.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid School", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String gradestr = gradetxt.getText();
        double grade;
        try {
            grade = Double.parseDouble(gradestr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid average grade", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String studentimpactedstr = studentimpactedtxt.getText();
        int studentimpacted;
        try {
            studentimpacted = Integer.parseInt(studentimpactedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter the valid number student impacted", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String moneydonatedstr = moneydonatedtxt.getText();
        double moneydonated;
        try {
            moneydonated = Double.parseDouble(moneydonatedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid money donated", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String text = texttxt.getText();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid text", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Category cat = (Category) categorycombo.getSelectedItem();

        Project proj = new Project(title_description, fundingGoal, type,
                grade, School, studentimpacted,
                cat);
        projects.addProject(proj);

        JOptionPane.showMessageDialog(AddProject.this, ""
                + " Project added successfully !", "Adding Projects", JOptionPane.INFORMATION_MESSAGE);

        
        model.addElement(proj);
        projectslist.setSelectedValue(projects, true);
    }//GEN-LAST:event_addbtn1ActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        titledescriptiontxt.setText("");
        typetxt.setText("");
        fundingGoaltxt.setText("");
        schooltxt.setText("");
        gradetxt.setText("");
        studentimpactedtxt.setText("");
        moneydonatedtxt.setText("");
        texttxt.setText("");
        
    }//GEN-LAST:event_clearbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn1;
    private javax.swing.JComboBox<Category> categorycombo;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField fundingGoaltxt;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField moneydonatedtxt;
    private javax.swing.JTextField schooltxt;
    private javax.swing.JTextField studentimpactedtxt;
    private javax.swing.JTextField texttxt;
    private javax.swing.JTextField titledescriptiontxt;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import donorschooseapplication.project.Category;

/**
 *
 * @author asoual
 */
import static GUI.ProjectsFrame.projects;
import static GUI.DisplayProject.model;
import static GUI.DisplayProject.projectslist;
import donorschooseapplication.project.Project;
import javax.swing.JOptionPane;


public class AddProject extends javax.swing.JPanel {

    /**
     * Creates new form AddProject
     */
    public AddProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        titledescriptiontxt = new javax.swing.JTextField();
        fundingGoaltxt = new javax.swing.JTextField();
        schooltxt = new javax.swing.JTextField();
        gradetxt = new javax.swing.JTextField();
        studentimpactedtxt = new javax.swing.JTextField();
        moneydonatedtxt = new javax.swing.JTextField();
        texttxt = new javax.swing.JTextField();
        categorycombo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        addbtn1 = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Create.png"))); // NOI18N
        jLabel1.setText("Add a New Project");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Title Description");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("type");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("funding Goal");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("School");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("avg Student Grade");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("nb of student Impacted");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Money Donated");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("text");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Category");

        typetxt.setBackground(new java.awt.Color(255, 255, 255));
        typetxt.setForeground(new java.awt.Color(51, 51, 51));

        titledescriptiontxt.setBackground(new java.awt.Color(255, 255, 255));
        titledescriptiontxt.setForeground(new java.awt.Color(51, 51, 51));
        titledescriptiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titledescriptiontxtActionPerformed(evt);
            }
        });

        fundingGoaltxt.setBackground(new java.awt.Color(255, 255, 255));
        fundingGoaltxt.setForeground(new java.awt.Color(51, 51, 51));

        schooltxt.setBackground(new java.awt.Color(255, 255, 255));
        schooltxt.setForeground(new java.awt.Color(51, 51, 51));

        gradetxt.setBackground(new java.awt.Color(255, 255, 255));
        gradetxt.setForeground(new java.awt.Color(51, 51, 51));
        gradetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradetxtActionPerformed(evt);
            }
        });

        studentimpactedtxt.setBackground(new java.awt.Color(255, 255, 255));
        studentimpactedtxt.setForeground(new java.awt.Color(51, 51, 51));

        moneydonatedtxt.setBackground(new java.awt.Color(255, 255, 255));
        moneydonatedtxt.setForeground(new java.awt.Color(51, 51, 51));

        texttxt.setBackground(new java.awt.Color(255, 255, 255));
        texttxt.setForeground(new java.awt.Color(51, 51, 51));

        categorycombo.setBackground(new java.awt.Color(255, 255, 255));
        categorycombo.setForeground(new java.awt.Color(51, 51, 51));
        categorycombo.setModel(new javax.swing.DefaultComboBoxModel<>(Category.values()));

        addbtn1.setBackground(new java.awt.Color(255, 255, 255));
        addbtn1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        addbtn1.setForeground(new java.awt.Color(0, 0, 0));
        addbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Create.png"))); // NOI18N
        addbtn1.setText("Add");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(255, 255, 255));
        clearbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(51, 51, 51));
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Abort.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titledescriptiontxt)
                    .addComponent(typetxt)
                    .addComponent(fundingGoaltxt)
                    .addComponent(schooltxt)
                    .addComponent(gradetxt)
                    .addComponent(studentimpactedtxt)
                    .addComponent(moneydonatedtxt)
                    .addComponent(texttxt)
                    .addComponent(categorycombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(addbtn1)
                        .addGap(88, 88, 88)
                        .addComponent(clearbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titledescriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fundingGoaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(schooltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentimpactedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(moneydonatedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn1)
                    .addComponent(clearbtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titledescriptiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titledescriptiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titledescriptiontxtActionPerformed

    private void gradetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradetxtActionPerformed

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
        // TODO add your handling code here:

        String title_description = titledescriptiontxt.getText();
        if (title_description.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid title", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type = typetxt.getText();
        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid type", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fundingGoalstr = fundingGoaltxt.getText();
        double fundingGoal;
        try {
            fundingGoal = Double.parseDouble(fundingGoalstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid funding Goal", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String School = schooltxt.getText();
        if (School.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid School", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String gradestr = gradetxt.getText();
        double grade;
        try {
            grade = Double.parseDouble(gradestr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid average grade", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String studentimpactedstr = studentimpactedtxt.getText();
        int studentimpacted;
        try {
            studentimpacted = Integer.parseInt(studentimpactedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter the valid number student impacted", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String moneydonatedstr = moneydonatedtxt.getText();
        double moneydonated;
        try {
            moneydonated = Double.parseDouble(moneydonatedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid money donated", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String text = texttxt.getText();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(AddProject.this, ""
                    + " Enter a valid text", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Category cat = (Category) categorycombo.getSelectedItem();

        Project proj = new Project(title_description, fundingGoal, type,
                grade, School, studentimpacted,
                cat);
        projects.addProject(proj);

        JOptionPane.showMessageDialog(AddProject.this, ""
                + " Project added successfully !", "Adding Projects", JOptionPane.INFORMATION_MESSAGE);

        
        model.addElement(proj);
        projectslist.setSelectedValue(projects, true);
    }//GEN-LAST:event_addbtn1ActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        titledescriptiontxt.setText("");
        typetxt.setText("");
        fundingGoaltxt.setText("");
        schooltxt.setText("");
        gradetxt.setText("");
        studentimpactedtxt.setText("");
        moneydonatedtxt.setText("");
        texttxt.setText("");
        
    }//GEN-LAST:event_clearbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn1;
    private javax.swing.JComboBox<Category> categorycombo;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField fundingGoaltxt;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField moneydonatedtxt;
    private javax.swing.JTextField schooltxt;
    private javax.swing.JTextField studentimpactedtxt;
    private javax.swing.JTextField texttxt;
    private javax.swing.JTextField titledescriptiontxt;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
