/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.ProjectsFrame.projects;
import donorschooseapplication.project.Category;
import donorschooseapplication.project.Project;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asoual
 */
public class DisplayProject extends javax.swing.JPanel {
    static DefaultListModel<Project> model;
    /**
     * Creates new form DisplayProject
     */
    public DisplayProject() {
        model = new DefaultListModel<>();
        initComponents();
        projectslist.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titledecriptiontxt = new javax.swing.JTextField();
        typetxt = new javax.swing.JTextField();
        fundinggoaltxt = new javax.swing.JTextField();
        schooltxt = new javax.swing.JTextField();
        gradetxt = new javax.swing.JTextField();
        studentimpactedtxt = new javax.swing.JTextField();
        moneydonatedtxt = new javax.swing.JTextField();
        texttxt = new javax.swing.JTextField();
        categorystr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectslist = new javax.swing.JList<>();
        projects = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Display 16x16.png"))); // NOI18N
        jLabel1.setText("Display selescted Project");

        jLabel2.setText("title description");

        jLabel3.setText("type");

        jLabel4.setText("funding Goal");

        jLabel5.setText("School");

        jLabel6.setText("avg student Grade");

        jLabel7.setText("nb of student impacted");

        jLabel8.setText("Money donated");

        jLabel9.setText("text");

        jLabel10.setText("Category");

        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        texttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttxtActionPerformed(evt);
            }
        });

        projectslist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        projectslist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projectslistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(projectslist);

        projects.setText("Projects");

        editbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projects)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editbtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titledecriptiontxt)
                                    .addComponent(typetxt)
                                    .addComponent(fundinggoaltxt)
                                    .addComponent(schooltxt)
                                    .addComponent(gradetxt)
                                    .addComponent(studentimpactedtxt)
                                    .addComponent(moneydonatedtxt)
                                    .addComponent(texttxt)
                                    .addComponent(categorystr, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deletebtn)
                                .addGap(96, 96, 96))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titledecriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(projects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fundinggoaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(schooltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(studentimpactedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(moneydonatedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(categorystr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbtn)
                    .addComponent(deletebtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    private void texttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttxtActionPerformed

    private void projectslistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectslistValueChanged
        // TODO add your handling code here:
        if ( evt.getValueIsAdjusting())
            return;
        Project proj = projectslist.getSelectedValue();
        if ( proj ==null)
            return ;
        titledecriptiontxt.setText(proj.getTitle_description());
        typetxt.setText(proj.getType());
        fundinggoaltxt.setText(String.valueOf(proj.getFunding_goal()));
        schooltxt.setText(proj.getSchool());
        gradetxt.setText(String.valueOf(proj.getStudent_grade()));
        studentimpactedtxt.setText(String.valueOf(proj.getNb_student_impacted()));
        moneydonatedtxt.setText(String.valueOf(proj.getMoney_donated()));
        texttxt.setText(proj.getText());
        categorystr.setText(proj.getCategory().name());
    }//GEN-LAST:event_projectslistValueChanged

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        String title_description = titledecriptiontxt.getText();
        if (title_description.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid title", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type = typetxt.getText();
        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid type", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fundingGoalstr = fundinggoaltxt.getText();
        double fundingGoal;
        try {
            fundingGoal = Double.parseDouble(fundingGoalstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid funding Goal", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String School = schooltxt.getText();
        if (School.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject./*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.ProjectsFrame.projects;
import donorschooseapplication.project.Category;
import donorschooseapplication.project.Project;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asoual
 */
public class DisplayProject extends javax.swing.JPanel {
    static DefaultListModel<Project> model;
    /**
     * Creates new form DisplayProject
     */
    public DisplayProject() {
        model = new DefaultListModel<>();
        initComponents();
        projectslist.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        titledecriptiontxt = new javax.swing.JTextField();
        typetxt = new javax.swing.JTextField();
        fundinggoaltxt = new javax.swing.JTextField();
        schooltxt = new javax.swing.JTextField();
        gradetxt = new javax.swing.JTextField();
        studentimpactedtxt = new javax.swing.JTextField();
        moneydonatedtxt = new javax.swing.JTextField();
        texttxt = new javax.swing.JTextField();
        categorystr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectslist = new javax.swing.JList<>();
        projects = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Display 16x16.png"))); // NOI18N
        jLabel1.setText("Display selescted Project");

        jLabel2.setText("title description");

        jLabel3.setText("type");

        jLabel4.setText("funding Goal");

        jLabel5.setText("School");

        jLabel6.setText("avg student Grade");

        jLabel7.setText("nb of student impacted");

        jLabel8.setText("Money donated");

        jLabel9.setText("text");

        jLabel10.setText("Category");

        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        texttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttxtActionPerformed(evt);
            }
        });

        projectslist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        projectslist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projectslistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(projectslist);

        projects.setText("Projects");

        editbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projects)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editbtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titledecriptiontxt)
                                    .addComponent(typetxt)
                                    .addComponent(fundinggoaltxt)
                                    .addComponent(schooltxt)
                                    .addComponent(gradetxt)
                                    .addComponent(studentimpactedtxt)
                                    .addComponent(moneydonatedtxt)
                                    .addComponent(texttxt)
                                    .addComponent(categorystr, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deletebtn)
                                .addGap(96, 96, 96))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titledecriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(projects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fundinggoaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(schooltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(gradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(studentimpactedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(moneydonatedtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(categorystr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbtn)
                    .addComponent(deletebtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    private void texttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttxtActionPerformed

    private void projectslistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectslistValueChanged
        // TODO add your handling code here:
        if ( evt.getValueIsAdjusting())
            return;
        Project proj = projectslist.getSelectedValue();
        if ( proj ==null)
            return ;
        titledecriptiontxt.setText(proj.getTitle_description());
        typetxt.setText(proj.getType());
        fundinggoaltxt.setText(String.valueOf(proj.getFunding_goal()));
        schooltxt.setText(proj.getSchool());
        gradetxt.setText(String.valueOf(proj.getStudent_grade()));
        studentimpactedtxt.setText(String.valueOf(proj.getNb_student_impacted()));
        moneydonatedtxt.setText(String.valueOf(proj.getMoney_donated()));
        texttxt.setText(proj.getText());
        categorystr.setText(proj.getCategory().name());
    }//GEN-LAST:event_projectslistValueChanged

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        String title_description = titledecriptiontxt.getText();
        if (title_description.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid title", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type = typetxt.getText();
        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid type", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fundingGoalstr = fundinggoaltxt.getText();
        double fundingGoal;
        try {
            fundingGoal = Double.parseDouble(fundingGoalstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid funding Goal", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String School = schooltxt.getText();
        if (School.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid School", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String gradestr = gradetxt.getText();
        double grade;
        try {
            grade = Double.parseDouble(gradestr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid average grade", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String studentimpactedstr = studentimpactedtxt.getText();
        int studentimpacted;
        try {
            studentimpacted = Integer.parseInt(studentimpactedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter the valid number student impacted", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String moneydonatedstr = moneydonatedtxt.getText();
        double moneydonated;
        try {
            moneydonated = Double.parseDouble(moneydonatedstr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid money donated", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;

        }
        String text = texttxt.getText();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(DisplayProject.this, ""
                    + " Enter a valid text", "Adding Projects", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String cate = categorystr.getText();
        Category cat = Category.valueOf(cate);


        Project proj = new Project(title_description, fundingGoal, type,
                grade, School, studentimpacted,
                cat);
        

        JOptionPane.showMessageDialog(DisplayProject.this, ""
                + " Project added successfully !", "Adding Projects", JOptionPane.INFORMATION_MESSAGE);

        
        model.addElement(proj);
        projectslist.setSelectedValue(projects, true);
    
    }//GEN-LAST:event_editbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
           
        int selectedIndex = projectslist.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
         }
    }//GEN-LAST:event_deletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categorystr;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField fundinggoaltxt;
    private javax.swing.JTextField gradetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField moneydonatedtxt;
    private javax.swing.JLabel projects;
    static javax.swing.JList<Project> projectslist;
    private javax.swing.JTextField schooltxt;
    private javax.swing.JTextField studentimpactedtxt;
    private javax.swing.JTextField texttxt;
    private javax.swing.JTextField titledecriptiontxt;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
