/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import donorschooseapplication.project.Category;
import javax.swing.table.DefaultTableModel;
import static GUI.ProjectsFrame.projects;
import donorschooseapplication.project.Project;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author asoual
 */
public class SearchProject extends javax.swing.JPanel {

    DefaultTableModel model;
    String[] colNames = {"title description", "type", "funding goal", "school",
        "average student grade", "nb of student impacted", "money donated", "text", "Category"};

    /**
     * Creates new form SearchProject
     */
    public SearchProject() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(colNames);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        categorytxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultstable = new javax.swing.JTable();
        saerchbtn = new javax.swing.JButton();

        jLabel1.setText("Search Projects by categories");

        jLabel2.setText("Category :");

        jLabel3.setText("Search results");

        resultstable.setModel(model);
        jScrollPane1.setViewportView(resultstable);

        saerchbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        saerchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Search.png"))); // NOI18N
        saerchbtn.setText("search");
        saerchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saerchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(saerchbtn)))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saerchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saerchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saerchbtnActionPerformed
        // TODO add your handling code here:
        String categorystr = categorytxt.getText();

        Category cat = Category.valueOf(categorystr);

        List <Project> proj = projects.findprojectwithCategory(categorystr);
        if (!proj.isEmpty()){
            Object [][] data = new Object [proj.size()][colNames.length];
            for(int i=0;i<proj.size();i++){
                Project pro = proj.get(i);
                data[i][0]= pro.getTitle_description();
                data[i][1]= pro.getType();
                data[i][2]= pro.getFunding_goal();
                data[i][3]= pro.getSchool();
                data[i][4]= pro.getStudent_grade();
                data[i][5]= pro.getNb_student_impacted();
                data[i][6]= pro.getMoney_donated();
                data[i][7]= pro.getText();
                data[i][8]= pro.getCategory();
            }
            model.setDataVector(data, colNames);
            
            
            
        }else {
            model.setDat/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import donorschooseapplication.project.Category;
import javax.swing.table.DefaultTableModel;
import static GUI.ProjectsFrame.projects;
import donorschooseapplication.project.Project;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author asoual
 */
public class SearchProject extends javax.swing.JPanel {

    DefaultTableModel model;
    String[] colNames = {"title description", "type", "funding goal", "school",
        "average student grade", "nb of student impacted", "money donated", "text", "Category"};

    /**
     * Creates new form SearchProject
     */
    public SearchProject() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(colNames);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        categorytxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultstable = new javax.swing.JTable();
        saerchbtn = new javax.swing.JButton();

        jLabel1.setText("Search Projects by categories");

        jLabel2.setText("Category :");

        jLabel3.setText("Search results");

        resultstable.setModel(model);
        jScrollPane1.setViewportView(resultstable);

        saerchbtn.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        saerchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guis/icons/Search.png"))); // NOI18N
        saerchbtn.setText("search");
        saerchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saerchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(saerchbtn)))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saerchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saerchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saerchbtnActionPerformed
        // TODO add your handling code here:
        String categorystr = categorytxt.getText();

        Category cat = Category.valueOf(categorystr);

        List <Project> proj = projects.findprojectwithCategory(categorystr);
        if (!proj.isEmpty()){
            Object [][] data = new Object [proj.size()][colNames.length];
            for(int i=0;i<proj.size();i++){
                Project pro = proj.get(i);
                data[i][0]= pro.getTitle_description();
                data[i][1]= pro.getType();
                data[i][2]= pro.getFunding_goal();
                data[i][3]= pro.getSchool();
                data[i][4]= pro.getStudent_grade();
                data[i][5]= pro.getNb_student_impacted();
                data[i][6]= pro.getMoney_donated();
                data[i][7]= pro.getText();
                data[i][8]= pro.getCategory();
            }
            model.setDataVector(data, colNames);
            
            
            
        }else {
            model.setDataVector(null, colNames);
            JOptionPane.showMessageDialog(SearchProject.this, "nothing found"
                    , "searching projects", JOptionPane.INFORMATION_MESSAGE);
            return;
            
        }
    }//GEN-LAST:event_saerchbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categorytxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable resultstable;
    private javax.swing.JButton saerchbtn;
    // End of variables declaration//GEN-END:variables
}
